### PR TITLE
Switch to Buildkite for publishing

### PR DESCRIPTION
**Pull request by toolmantim**
This switches to Makefile targets that are the same in dev and in CI, rather than having two different scripts. And it switches to running Helm in a Docker container, so the only tools needed to run this in CI are Make, Docker and Git.

If you run `make build` in a fresh checkout, you should end up with a `dist-repo` directory which is a `gh-pages` checkout of the main repo, re-indexed with any newly build packages.

```
$ make clean build
rm -rf dist-repo
git clone --quiet --single-branch -b gh-pages "https://github.com/buildkite/charts.git" dist-repo
cd package && \
		docker-compose build && \
		docker-compose run --rm package package.sh "https://buildkite.github.io/charts" dist-repo && \
		cd ../dist-repo && \
		echo "--- Diff" && \
		git diff --stat
Building package
Step 1/3 : FROM alpine
 ---> 196d12cf6ab1
Step 2/3 : RUN apk add --update bash openssl curl git     && (curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash)     && helm init --client-only
 ---> Using cache
 ---> 72b5acb93ffc
Step 3/3 : COPY package.sh /usr/sbin/
 ---> Using cache
 ---> edbc9837b927

Successfully built edbc9837b927
Successfully tagged package_package:latest
--- Packaging ./stable/agent into dist-repo
No requirements found in /charts/stable/agent/charts.
Successfully packaged chart and saved it to: dist-repo/agent-0.3.3.tgz
--- Reindexing dist-repo
LICENSE          agent-0.3.1.tgz  agent-0.3.2.tgz  agent-0.3.3.tgz  index.yaml
--- Diff
 agent-0.3.3.tgz | Bin 6170 -> 6170 bytes
 index.yaml      |  48 +++++++++++++++++++++++++++++++++++++++++++++---
 2 files changed, 45 insertions(+), 3 deletions(-)
```

You can then run `make release` to commit and push the changes. And it works in CI, or locally.

What do you reckon @rimusz?

Also I noticed the published `gh-pages` index.yaml is missing the older chart versions, and seems only to have the latest one (hence the large diff in the output above). Perhaps a bug that I've fixed in this version?

### CODE REVIEW

**Comment by rimusz** [comment]
LGTM, but I see that these errors:
```
make shellcheck
--
  | /bin/bash: make: command not found

```

**Comment by rimusz** [comment]
`gh-pages index.yaml is missing the older chart versions` yes we need that working

**Comment by toolmantim** [comment]
Alright, I've fixed the test steps, and moved the deploy step into its own pipeline that can be triggered/run completely separately while we get that working.

Are you okay with me having removed the Cloud Build config whilst we get it working, or should we re-add it in but change it to use the `make build release` task? I'm okay if you want to do that!

**Comment by toolmantim** [comment]
Hah! You beat me to the submit button 😁

**Comment by toolmantim** [comment]
I can confirm the "missing the older chart versions" is fixed in this `make build release` version too 👌🏼

Do we only want automatic releases to happen on all master commits, or only on `v*.*` tags?

**Comment by rimusz** [comment]
`v*.*` tags also would be good :)

**Comment by toolmantim** [comment]
Sounds like we probably shouldn't publish on every commit to master then (because that would keep re-publishing things that don't bump the version number)? But only publish when a new `v*.*` or `v*.*.*` tag is pushed?

**Comment by rimusz** [comment]
yes, makes sense, let's only publish when the new `v*.*` or `v*.*.*` tag is pushed

**Comment by toolmantim** [comment]
👌🏼

**Comment by rimusz** [comment]
@toolmantim I implemented charts install test for my personal charts https://github.com/rimusz/charts/blob/master/.circleci/config.yml#L26-L39 and https://github.com/rimusz/charts/blob/master/test/e2e-kind.sh 

But we need so dummy BK `token` we can pass so bk agent doesn't crash :)

Example https://github.com/rimusz/charts/blob/master/stable/hostpath-provisioner/ci/test-values.yaml

So we need to create a file `ci/test-values.yaml`:
```
agent:
  # Your Buildkite agent token, it must be set
  token: "dummy_token"
```
In such setup `ct` will use that file to do the test install :)

**Pull request merged**
