### PR TITLE
feat: handle docker config for multiple purpose

### PR DESCRIPTION
**Pull request by amalucelli**
**What this PR does / why we need it**: Handle the docker config file in two different situations, the first is to authenticate the docker client over the `Pod`, and the other one is to use over the `imagePullSecrets` for custom images for the Buildkite agent.

**Special notes for your reviewer**:
- I saw that the current variable wasn't used with the type of `kubernetes.io/dockerconfigjson`, so I imagine that the purpose was to mount to be use directly with the docker client, that why I renamed the file to `config.json`;
- Added a second attribute to handle the `dockerconfigjson`, where uses the type of `kubernetes.io/dockerconfigjson` and can be only used for the `Pod` specification;

#### Checklist
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by gzamboni — APPROVED** [review]

**Review by caarlos0 — APPROVED** [review]
lgtm

**Comment by rimusz** [comment]
awesome, thanks for the PR @amalucelli and @gzamboni @caarlos0 for reviewing it 👍

**Comment by rimusz** [comment]
released

**Comment by amalucelli** [comment]
that's awesome @rimusz, thanks for the quickly interaction, I already update our repo! you guys rock! 🚀

**Comment by rimusz** [comment]
you welcome :)

**Comment by toolmantim** [comment]
All credit goes to @rimusz!

**Comment by caarlos0** [comment]
🚀 thanks everyone!

**Pull request merged**
