### PR TITLE
Option to remove ineffective graceful shutdown code

### PR DESCRIPTION
**Pull request by abhishekmukherg**
What this PR does / why we need it: This PR removes the preStop lifecycle hook intended for graceful shutdown, because is actually killing both the agent and the job immediately. The default behaviour of the terminationGracePeriodSeconds variable is already taking care of gracefully shutting down the pods.
The code for tini only forwards the signals to the process which it specifically starts, not all children processes.

Note that this is a successor to #87 with the feedback from @rimusz. @DavidVtwilio is on PTO so thought I'd quickly hack this together. I'm hoping this is about what you were asking for? The behavior, by default, remains the same. I've also through in relevant hooks for just straight up overriding the preStop and postStart lifecycle.

Please also note that I do not have full confidence in my Helm abilities -- especially my Helm stylistic ability.

### CODE REVIEW

**Comment by calvinbui** [comment]
`-q` in `pidof` is not a valid option. I changed my preStop command to this and it's working successfully to get the lowest PID: 

```
kill $(pidof buildkite-agent | tr -s ' ' '\n' | sort -n | sed '1q'); while pidof buildkite-agent > /dev/null; do sleep 1; done
```

If using `dind`, that container will be stopped before the `agent` container is stopped. To fix this I use the `BUILDKITE_AGENT_HEALTH_CHECK_ADDR` variable and had a preStop on the `dind` container to stop after the `agent` container stopped:

```
while wget --quiet --output-document /dev/null http://localhost:19303; do sleep 1; done
```

**Comment by rimusz** [comment]
@calvinbui would you mind to do a PR with that fix?

**Comment by abhishekmukherg** [comment]
@rimusz Forgive me, I'm very new to helm, but did I break the contract for "should remain the same" by not specifying a `| default`? I'm trying to test this as a subchart dependency right now and I think I must be doing something wrong on my end, but figured I'd reach out in case I _did_ break it. Specifically, I'm expecting a no-op change of just updating to have no changes, but I am in fact seeing changes -- the lifecycle is disappearing 😬 . Even more specifically, it was working when used in the chart itself as I was creating this PR, but failing when in a subchart

**Comment by abhishekmukherg** [comment]
Oh no, I believe I have forgotten to bump the version of this chart in this pull request. Because of that, I believe we've overridden the version 0.5.2 of this chart with the version I believe should be 0.5.3 I think 0.5.2 may need to be recreated and this version needs to be bumped

**Pull request merged**
