### PR TITLE
Switch CI to Buildkite

### PR DESCRIPTION
**Pull request by toolmantim**
I've set this up on Buildkite w/ our public builds beta:
https://buildkite.com/buildkite-oss/helm-charts

It means we can switch off Circle now, though this doesn't test third-party forks yet.

I'd like to switch the deploy step to Buildkite too, but that's a work-in-progress as we work on some new agent Docker images that can access AWS secretsmanager for the GH access token.

### CODE REVIEW

**Comment by rimusz** [comment]
@toolmantim that looks good.
pity we cannot test third-party forks yet, this the main reason why I was using CircleCI.

Also I would love to introduce chart install test as well, it is also done by `ct` tool, but we need
some dummy Buildkite Agent `token` to pass to chart, so agent doesn't crash.
The `ct` install needs Kubernetes cluster, which can in CircleCI pipeline step, I was going to use https://github.com/kubernetes-sigs/kubeadm-dind-cluster for it, not sure how we can do that with https://buildkite.com/buildkite-oss/helm-charts

I'm happy to keep the deploy part with my Cloud Build till you sort that part out.

**Comment by rimusz** [comment]
suggestion, for the mean time we should keep CircleCI to test third-party forks

**Comment by toolmantim** [comment]
Happy to help with getting kubeadm-dind-cluster working. Seeing as you put back the Circle config, I can just port it across as ncessary.

How can I help get the chart install test working?

**Comment by rimusz** [comment]
For the `agent` chart install test working first we need some dummy Buildkite Agent `token` we can pass to chart, so agent doesn't crash, then I can chip in onto `kind` in CircleCI, and then you can port it to BK pipeline.

**Comment by rimusz** [comment]
btw deploy part shouldn't be too difficult to port to BK pipeline.

**Comment by toolmantim** [comment]
I just set up an charts integration test org, and invited you as an admin, so you can grab an agent token from there for the chart install test.

**Comment by rimusz** [comment]
ok, but that token needs to be hidden, in circleci it can only be used for PRs from main repo.
we need to sort out for PRs from forks how to do the full chart liting and install cycle.

**Comment by toolmantim** [comment]
I assumed Circle had a way of doing that? For the BK CI, I can actually create an agent access token via GraphQL before the job, and destroy it after the job, so it's only ever valid for a single CI run. Is that more what you're thinking?

**Comment by toolmantim** [comment]
But there's other reasons I can't enable fork testing on the Buildkite CI stuff at the moment (but hopefully soon)

**Comment by rimusz** [comment]
circleci can only securely hide for PRs from the main repo, as we do not want expose any sensitive information for PRs from forks.

I think for now then we should use circleci for linting charts from PRs from forks.
Buildkite for linting and install testing fro PRs from the main repo and merge to master to do the chart release to gh-pages

**Comment by toolmantim** [comment]
I reckon we can figure out the fork testing too.

**Comment by rimusz** [comment]
of course we can :)

**Pull request merged**
