### PR TITLE
Publish automaticly to gh-pages, lint charts from PR

### PR DESCRIPTION
**Pull request by rimusz**

### CODE REVIEW

**Comment by rimusz** [comment]
it all happens inside the TravisCI VM, nothing gets touched in git repo.
`ct` is the tool https://github.com/helm/chart-testing which is used to check `helm/charts` and is recommended to use to check your charts, specially if you want your helm repo to be part of new helm distributed repo called hub (not available yet).

**Comment by toolmantim** [comment]
Okay cool. So if `ct` doesn’t use that, what’s the purpose of the two git remote lines then? Just so I know how to get it working in BK.

**Comment by toolmantim** [comment]
(For context, we have public builds in beta, and I wanted to test it on this repo)

**Comment by rimusz** [comment]
`ct` needs access to git repo master which is done via remote (read it only) so it can compare charts for changes

**Pull request merged**
